name       : python-dbusmock
version    : 0.27.5
release    : 10
source     :
    - https://github.com/martinpitt/python-dbusmock/archive/refs/tags/0.27.5.tar.gz : c951dcb6eba1ff73c06f7c71c52bd528d135e233c8376729c62d30e1ed2206b8
homepage   : https://github.com/martinpitt/python-dbusmock
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Mock D-Bus objects for tests
description: |
    With this program/Python library you can easily create mock objects on D-Bus. This is useful for writing tests for software which talks to D-Bus services such as upower, systemd, logind, gnome-session or others, and it is hard (or impossible without root privileges) to set the state of the real services to what you expect in your tests.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
