name       : python-dbusmock
version    : 0.24.1
release    : 7
source     :
    - https://github.com/martinpitt/python-dbusmock/archive/refs/tags/0.24.1.tar.gz : 268ec93cec49d103e7f1d01e50f34ef1797932b9c3933e2721505a507473280f
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Mock D-Bus objects for tests
description: |
    Mock D-Bus objects for tests
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
