name       : python-dbusmock
version    : 0.24.0
release    : 6
source     :
    - https://github.com/martinpitt/python-dbusmock/archive/refs/tags/0.24.0.tar.gz : 611618b0a8b7af371a05b65391918960ee47bbb46b95ece8fa9d722f942866f3
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Mock D-Bus objects for tests
description: |
    Mock D-Bus objects for tests
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
