name       : python-dbusmock
version    : 0.29.1
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/p/python-dbusmock/python-dbusmock-0.29.1.tar.gz : b03590057c236d352c38973f4b71ae2c97b3a1cb1dc6f03278ce4072a3716a74
homepage   : https://github.com/martinpitt/python-dbusmock
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Mock D-Bus objects for tests
description: |
    With this program/Python library you can easily create mock objects on D-Bus. This is useful for writing tests for software which talks to D-Bus services such as upower, systemd, logind, gnome-session or others, and it is hard (or impossible without root privileges) to set the state of the real services to what you expect in your tests.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    # build with PEP517
    rm setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
