name       : python-dbusmock
version    : '0.19'
release    : 2
source     :
    - https://github.com/martinpitt/python-dbusmock/archive/0.19.tar.gz : 3133e8331d62351ddadd085b93a0bc8ffbc5543398053e92c452f9c3fa0c0d34
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Mock D-Bus objects for tests
description: |
    Mock D-Bus objects for tests
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-dbus
    - python-gobject
setup      : |
    %python3_setup
install    : |
    %python3_install
